# Docker compose for PaF2023
version: '3.7'

services:
  paf-db:
    image: postgres:latest
    restart: always
    container_name: paf-db
    labels:
      project: "PaF 2023"
      component: "AppDatabase for PaF 2023"
      version: "1.0"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: paf2023
      POSTGRES_PASSWORD: paf2023
      POSTGRES_DB: paf2023
    volumes:
      # volume for postgres data
      - Paf2023PostgresVolume:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - pafNet

volumes:
  Paf2023PostgresVolume:

networks:
  pafNet:
    external: false
    name: pafNet

